spring:
  profiles:
    active: local
mybatis:
  type-aliases-package: com.zspace.mybatis.demo.entity
  mapper-locations: classpath:mappers/*Mapper.xml


---
# 本地环境
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/crawl?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
